localStorage.getItem("hboa")
    ? ((document.getElementById("boa1").innerHTML = localStorage.getItem("boa1")),
      (document.getElementById("boa2").innerHTML = localStorage.getItem("boa2")),
      (document.getElementById("boa3").innerHTML = localStorage.getItem("boa3")),
      (document.getElementById("boa4").innerHTML = localStorage.getItem("boa4")),
      (document.getElementById("boa5").innerHTML = localStorage.getItem("boa5")),
      (document.getElementById("boa6").innerHTML = localStorage.getItem("boa6")),
      (document.getElementById("boa7").innerHTML = localStorage.getItem("boa7")),
      (document.getElementById("boa8").innerHTML = localStorage.getItem("boa8")),
      (document.getElementById("boa9").innerHTML = localStorage.getItem("boa9")),
      (document.getElementById("boa10").innerHTML = localStorage.getItem("boa10")),
      (document.getElementById("boa11").innerHTML = localStorage.getItem("boa11")),
      (document.getElementById("boa01").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa1").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa02").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa2").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa03").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa3").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa04").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa4").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa05").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa5").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa06").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa6").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa07").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa7").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa08").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa8").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa09").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa9").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa010").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa10").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa011").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa11").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()))
    : (
        localStorage.setItem("boa1", "$" + Math.floor(200 * Math.random() + 1125).toLocaleString()),
        localStorage.setItem("boa2", "$" + Math.floor(200 * Math.random() + 1325).toLocaleString()),
        localStorage.setItem("boa3", "$" + Math.floor(200 * Math.random() + 1525).toLocaleString()),
        localStorage.setItem("boa4", "$" + Math.floor(200 * Math.random() + 1725).toLocaleString()),
        localStorage.setItem("boa5", "$" + Math.floor(200 * Math.random() + 1925).toLocaleString()),
        localStorage.setItem("boa6", "$" + Math.floor(200 * Math.random() + 2125).toLocaleString()),
        localStorage.setItem("boa7", "$" + Math.floor(200 * Math.random() + 2325).toLocaleString()),
        localStorage.setItem("boa8", "$" + Math.floor(200 * Math.random() + 2525).toLocaleString()),
        localStorage.setItem("boa9", "$" + Math.floor(200 * Math.random() + 2725).toLocaleString()),
        localStorage.setItem("boa10", "$" + Math.floor(200 * Math.random() + 2925).toLocaleString()),
        localStorage.setItem("boa11", "$" + Math.floor(200 * Math.random() + 3125).toLocaleString()),

      (document.getElementById("boa1").innerHTML = localStorage.getItem("boa1")),
      (document.getElementById("boa2").innerHTML = localStorage.getItem("boa2")),
      (document.getElementById("boa3").innerHTML = localStorage.getItem("boa3")),
      (document.getElementById("boa4").innerHTML = localStorage.getItem("boa4")),
      (document.getElementById("boa5").innerHTML = localStorage.getItem("boa5")),
      (document.getElementById("boa6").innerHTML = localStorage.getItem("boa6")),
      (document.getElementById("boa7").innerHTML = localStorage.getItem("boa7")),
      (document.getElementById("boa8").innerHTML = localStorage.getItem("boa8")),
      (document.getElementById("boa9").innerHTML = localStorage.getItem("boa9")),
      (document.getElementById("boa10").innerHTML = localStorage.getItem("boa10")),
      (document.getElementById("boa11").innerHTML = localStorage.getItem("boa11")),
      (document.getElementById("boa01").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa1").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa02").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa2").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa03").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa3").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa04").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa4").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa05").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa5").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa06").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa6").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa07").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa7").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa08").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa8").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa09").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa9").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa010").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa10").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString()),
      (document.getElementById("boa011").innerHTML = "Buy: $" + parseFloat((localStorage.getItem("boa11").replace("$", "").replace(",", "") / 17.5).toFixed(0)).toLocaleString())),
    localStorage.setItem("hboa", !0);
